version: "3"

services:
  web:
    restart: always
    volumes:
      - ./web/prod-conf.d:/etc/nginx/conf.d:ro
      - ./web/includes:/etc/nginx/includes:ro
      - certs:/etc/letsencrypt:ro
      - snapshots:/data/snapshots:ro

  certbot:
    image: scummvm/certbot:latest
    restart: always
    networks:
      - web
    volumes:
      - certs:/etc/letsencrypt
    environment:
      DOMAINS: buildbot.scummvm.org

  buildbot:
    restart: always
    environment:
      # BUILDBOT_IRC_CHANNEL: "#scummvm"
      # BUILDBOT_IRC_USERNAME: ScummBot
      BUILDBOT_REPO_URL: https://github.com/scummvm/scummvm.git
      BUILDBOT_WEB_URL: https://buildbot.scummvm.org/
      SCUMMVM_DEV_ENV: 0
      SCUMMVM_SNAPSHOTS_URL: https://buildbot.scummvm.org/snapshots/

  buildbot-debian-x86_64:
    restart: always

  buildbot-amigaos:
    restart: always

  buildbot-android:
    restart: always

  buildbot-debian-x86:
    restart: always

  buildbot-dreamcast:
    restart: always

  buildbot-freemint:
    restart: always

  buildbot-gcw0:
    restart: always

  buildbot-haiku:
    restart: always

  buildbot-ios:
    restart: always

  buildbot-macos:
    restart: always

  buildbot-nintendo:
    restart: always

  buildbot-psp:
    restart: always

  buildbot-ps3:
    restart: always

  buildbot-raspberrypi:
    restart: always

  buildbot-vita:
    restart: always

  buildbot-windows:
    restart: always
